#!/usr/bin/env python

from __future__ import print_function
import re, sys, subprocess

avrdude='/usr/local/bin/avrdude'
proc = subprocess.Popen([avrdude]+sys.argv[1:], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdo,stde = proc.communicate()
rescode = proc.returncode

regex = '^(avrdude.*signature\s=\s0x[\da-fA-F]{6}).*'
for lijn in stdo.split('\n'):
    matchObj = re.match(regex, lijn, re.M|re.I)
    if matchObj:
        print(matchObj.group(1),file=sys.stdout)
    else:
        print(lijn,file=sys.stdout)

for lijn in stde.split('\n'):
    matchObj = re.match(regex, lijn, re.M|re.I)
    if matchObj:
        print(matchObj.group(1),file=sys.stderr)
    else:
        print(lijn,file=sys.stderr)

sys.exit(rescode)
